import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar/NavBar";

// providers
import { GoogleOAuthProvider } from "@react-oauth/google";
import { Provider } from "@/components/ui/provider";
import UserProvider from "@/context/UserContext";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Dayjob",
  description: "Generated by create next app",
};

export default function RootLayout ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>)
{
  return (
    <html lang="en">
      <body>
        <Provider>
          <GoogleOAuthProvider clientId="66052139702-l6jplgkm0kog6m2i58b97qjeq7i97dp9.apps.googleusercontent.com">
            <UserProvider>
              <main className="pt-14">
                <NavBar />
                {children}
              </main>
            </UserProvider>
          </GoogleOAuthProvider >
        </Provider>
      </body>
    </html>
  );
}
