# DAYJOB AND PARTS ARE ONE-MANY

#DROP SCHEMA DAYJOB_SCHEMA;

#CREATE DATABASE DAYJOB;

USE DAYJOB;

DROP TABLE DAYJOB_USER;
 DROP TABLE PARTS;
 DROP TABLE DAYJOB;


SELECT * FROM DAYJOB;
SELECT * FROM PARTS;

DELETE FROM PARTS WHERE PART_ID >= 0;
DELETE FROM DAYJOB WHERE DAYJOB_ID >= 0;

-- ALTER TABLE PARTS 
-- MODIFY COLUMN PART_SERIAL_NUMBER int; 

# USER AND DAYJOB ARE ONE-MANY
CREATE TABLE DAYJOB_USER (
	user_id int NOT NULL AUTO_INCREMENT PRIMARY KEY,	
	user_email varchar(30)
);

# DAYJOB AND PARTS ARE ONE-MANY
CREATE TABLE DAYJOB (
    dayjob_id int NOT NULL AUTO_INCREMENT,
    dayjob_date BIGINT,
    dayjob_serial_number int,
    dayjob_number int,
    dayjob_user_id int,
    PRIMARY KEY (DAYJOB_ID)
);

# PARTS AND PARTS_TYPE_MASTER ARE ONE-ONE
CREATE TABLE PARTS (
    part_id int NOT NULL AUTO_INCREMENT PRIMARY KEY,
    part_type varchar(10),
    part_number int,
    part_serial_number int,
    dayjob_id int,
    FOREIGN KEY (DAYJOB_ID) REFERENCES DAYJOB(DAYJOB_ID)
);

CREATE TABLE PARTS_TYPE_MASTER (
    PART_TYPE_ID int NOT NULL AUTO_INCREMENT,
    PART_NAME varchar(10),
    PART_NUMBER int,
    PART_ID int UNIQUE,
    PRIMARY KEY (PART_TYPE_ID),
    FOREIGN KEY (PART_ID) REFERENCES PARTS(PART_ID)
);
