# DAYJOB AND PARTS ARE ONE-MANY

#DROP SCHEMA DAYJOB_SCHEMA;

#CREATE DATABASE DAYJOB;

USE DAYJOB;

-- DROP TABLE PARTS_TYPE_MASTER;
-- DROP TABLE PARTS;
-- DROP TABLE DAYJOB;

# DAYJOB AND PARTS ARE ONE-MANY
CREATE TABLE DAYJOB (
    DAYJOB_ID int NOT NULL AUTO_INCREMENT,
    DAYJOB_DATE int,
    SERIAL_NUMBER int,
    USER_ID int,
    PRIMARY KEY (DAYJOB_ID)
);

# PARTS AND PARTS_TYPE_MASTER ARE ONE-ONE
CREATE TABLE PARTS (
    PART_ID int NOT NULL AUTO_INCREMENT PRIMARY KEY,
    PART_TYPE varchar(10),
    PART_NUMBER int,
    SERIAL_NUMBER int,
    DAYJOB_ID int,
    FOREIGN KEY (DAYJOB_ID) REFERENCES DAYJOB(DAYJOB_ID)
);

CREATE TABLE PARTS_TYPE_MASTER (
    PART_TYPE_ID int NOT NULL AUTO_INCREMENT,
    PART_NAME varchar(10),
    PART_NUMBER int,
    PART_ID int UNIQUE,
    PRIMARY KEY (PART_TYPE_ID),
    FOREIGN KEY (PART_ID) REFERENCES PARTS(PART_ID)
);
